/* Quimera_BD_Logico: */

CREATE TABLE IF NOT EXISTS Usuario (
    id INTEGER PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    usuario VARCHAR(255) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    login_ativo VARCHAR(1),
    nome_completo VARCHAR(255),
    data_nascimento DATE,
    UNIQUE (id, usuario)
);

CREATE TABLE IF NOT EXISTS Tarefa (
    id INTEGER PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR(255) NOT NULL,
    descricao VARCHAR(512),
    situacao VARCHAR(1),
    data_inicio DATE,
    data_fim DATE,
    id_usuario_criador INTEGER,
    usuario_id INTEGER,
    UNIQUE (id)
);
 
ALTER TABLE Tarefa ADD CONSTRAINT usuario_fk
    FOREIGN KEY (usuario_id)
    REFERENCES Usuario (id)
    ON DELETE SET NULL;
	